name: floracare_app
description: "FloraCare - Green Home App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  # 💡 مكتبة الذكاء الاصطناعي لتحليل الصور (موجودة وجاهزة لو أردت تفعيلها مستقبلاً)
  google_mlkit_image_labeling: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # 🌟 مكتبة توليد الأيقونات تمت إضافتها هنا
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# ============================================================================
# 🌟 إعدادات أيقونة التطبيق السحرية (Flutter Launcher Icons)
# ============================================================================
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  # إعدادات الأيقونة التكيفية (Adaptive) للأندرويد لكي تظهر بشكل فخم وممتاز
  adaptive_icon_background: "#F2F7F4" # لون الخلفية المائل للخضرة الخاص بتطبيقك
  adaptive_icon_foreground: "assets/logo.png"